// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqkzrvp6Pt8vV_zcLIBAvSaghIhvOJHB8',
    appId: '1:890977800846:web:4b734806c21126debcafdf',
    messagingSenderId: '890977800846',
    projectId: 'carry-along',
    authDomain: 'carry-along.firebaseapp.com',
    storageBucket: 'carry-along.appspot.com',
    measurementId: 'G-CYE17GT7GH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzAlAIekgUhOCiglPb_DpZFbzB1Ur0CAk',
    appId: '1:890977800846:android:b272026a8540c50abcafdf',
    messagingSenderId: '890977800846',
    projectId: 'carry-along',
    storageBucket: 'carry-along.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXRCHRyCpctlJjb0P5mGHdoMAL913skoc',
    appId: '1:890977800846:ios:8e95624c2e982499bcafdf',
    messagingSenderId: '890977800846',
    projectId: 'carry-along',
    storageBucket: 'carry-along.appspot.com',
    androidClientId: '890977800846-2tbupq6ru60a9uopf5a0l1981prg91s4.apps.googleusercontent.com',
    iosClientId: '890977800846-4142a96694enufvjiktp56m7sfutkclb.apps.googleusercontent.com',
    iosBundleId: 'com.example.carryAlong',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXRCHRyCpctlJjb0P5mGHdoMAL913skoc',
    appId: '1:890977800846:ios:8e95624c2e982499bcafdf',
    messagingSenderId: '890977800846',
    projectId: 'carry-along',
    storageBucket: 'carry-along.appspot.com',
    androidClientId: '890977800846-2tbupq6ru60a9uopf5a0l1981prg91s4.apps.googleusercontent.com',
    iosClientId: '890977800846-4142a96694enufvjiktp56m7sfutkclb.apps.googleusercontent.com',
    iosBundleId: 'com.example.carryAlong',
  );
}
